name: build docs
on: push
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip3 install pdoc3 appdirs pydub colorama
      - name: Build docs
        run: |
          pdoc --html qop -o docs
      - name: Commit documentation changes
        run: |
          git clone https://github.com/s-fleck/qop.git --branch gh-pages --single-branch gh-pages
          mv docs /tmp
          rm -r *
          mv /tmp/docs/qop/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "."
